// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const livraisonJpg = 'assets/images/livraison.jpg';
  static const livreeJpeg = 'assets/images/livree.jpeg';
  static const livreurJpg = 'assets/images/livreur.jpg';
  static const livreureJpg = 'assets/images/livreure.jpg';
  static const miagboImageJpeg = 'assets/images/miagbo_image.jpeg';
  static const profileeJpg = 'assets/images/profilee.jpg';
  static const ramassageJpg = 'assets/images/ramassage.jpg';
  static const ramasseJpg = 'assets/images/ramasse.jpg';
  static const transiJpeg = 'assets/images/transi.jpeg';
}

class AssetsSvgs {

}

